cfg:
  project_name: asl_classification
  seed: 42
  data:
    root_dir: data/raw/asl_alphabet_train/asl_alphabet_train
    batch_size: 64
    num_workers: 4
    img_size:
    - 200
    - 200
    input_channels: 3
    num_classes: 29
    val_split: 0.1
    test_split: 0.1
  model:
    lr: 0.001
    hidden_dim: 128
  trainer:
    max_epochs: 10
    accelerator: auto
    devices: 1
